### ISSUE TITLE
The ComfyUI-PuLID-Flux-Enhanced node is not installed

### ISSUE THREAD

**Issue by infoarg** [sipie800/ComfyUI-PuLID-Flux-Enhanced#10]
The ComfyUI-PuLID-Flux-Enhanced node is not installed. I tried to install it from the manager and manually in the folder E:\ComfyUI\ComfyUI_Windows_portable\ComfyUI\custom_nodes - the node is red. No error messages (!?) Clicking the blue "Try fix" button does not change anything - the node is still red. The node does not connect in any workspace where it is present. Please help me understand the problem.  ComfyUI version - updated.
Here is a significant fragment of the log related to this node:
## Execute install/(de)activation script for 'E:\ComfyUI\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced'
[2024-10-28 14:45:51.826]  Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
[2024-10-28 14:45:51.826]  Collecting facexlib
[2024-10-28 14:45:52.570]    Downloading facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)
[2024-10-28 14:45:52.848]  Collecting filterpy (from facexlib)
[2024-10-28 14:45:53.066]    Downloading filterpy-1.4.5.zip (177 kB)
[2024-10-28 14:45:53.143]    Preparing metadata (setup.py): started
[2024-10-28 14:45:53.366]    Preparing metadata (setup.py): finished with status 'error'
[2024-10-28 14:45:53.610] [!]   error: subprocess-exited-with-error
[2024-10-28 14:45:53.614] [!]   
[2024-10-28 14:45:53.614] [!]   python setup.py egg_info did not run successfully.
[2024-10-28 14:45:53.614] [!]   exit code: 1
[2024-10-28 14:45:53.614] [!]   
[2024-10-28 14:45:53.614] [!]   [6 lines of output]
[2024-10-28 14:45:53.614] [!]   Traceback (most recent call last):
[2024-10-28 14:45:53.614] [!]     File "<string>", line 2, in <module>
[2024-10-28 14:45:53.615] [!]     File "<pip-setuptools-caller>", line 34, in <module>
[2024-10-28 14:45:53.615] [!]     File "C:\Users\User\AppData\Local\Temp\pip-install-qiie3ol7\filterpy_828dbb2620d44be9a55a9842a0fe72fe\setup.py", line 4, in <module>
[2024-10-28 14:45:53.615] [!]       import filterpy
[2024-10-28 14:45:53.615] [!]   ModuleNotFoundError: No module named 'filterpy'
[2024-10-28 14:45:53.615] [!]   [end of output]
[2024-10-28 14:45:53.615] [!]   
[2024-10-28 14:45:53.616] [!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[2024-10-28 14:45:53.616] [!] 
[2024-10-28 14:45:54.562] [!] [notice] A new release of pip is available: 24.3 -> 24.3.1
[2024-10-28 14:45:54.562] [!] [notice] To update, run: E:\ComfyUI\ComfyUI_Windows_portable\python_embeded\python.exe -m pip install --upgrade pip
[2024-10-28 14:45:54.562] [!] error: metadata-generation-failed
[2024-10-28 14:45:54.562] [!] 
[2024-10-28 14:45:54.562] [!] Encountered error while generating package metadata.
[2024-10-28 14:45:54.562] [!] 
[2024-10-28 14:45:54.562] [!] See above for output.
[2024-10-28 14:45:54.562] [!] 
[2024-10-28 14:45:54.562] [!] note: This is an issue with the package mentioned above, not pip.
[2024-10-28 14:45:54.562] [!] hint: See above for details.
[2024-10-28 14:45:54.562] install/(de)activation script failed: E:\ComfyUI\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
[2024-10-28 14:45:54.640] 
[ComfyUI-Manager] Startup script completed.

**Comment by sipie800** [comment]
So far, this node is not meant to be installed from comfy manager, please try installing from code.
And it may conflicts with the original one, you can zip that node temporally.

**Comment by infoarg** [comment]
Thanks for your participation and quick response.
Installed via /custom_nodes, - not detected.
Disable original which one: https://github.com/balazik/ComfyUI-PuLID-Flux ?

**Comment by sipie800** [comment]
I'm sorry but I'm not fimiliar with comfy manager things and don't understand how you manage your comfyui.
If git clone doesn't work for you, you can also download the code zip from repo page and unzip to custom_nodes.
There is no need to run any setup things, if you have installed https://github.com/balazik/ComfyUI-PuLID-Flux before. It should work if the code file is present.

**Comment by infoarg** [comment]
The solution in my case:: python.exe -s -m pip install --use-pep517 facexlib

**Comment by HuaHuaFuxk** [comment]
Please tell me how to solve this problem. I have been looking for a solution for the whole day. Please

**Comment by infoarg** [comment]
Watch this video and repeat all the steps: https://www.youtube.com/watch?v=o_JOs56Q3zk
E:\ComfyUI\ComfyUI_Windows_portable\python_embeded>python.exe -m pip install --use-pep517 facexlib
