### ISSUE TITLE
In which directory should the file "EVA02_CLIP_L_336_psz14_s6B.pt" be placed?

### ISSUE THREAD

**Issue by Lethita** [sipie800/ComfyUI-PuLID-Flux-Enhanced#13]
!!! Exception during processing !!! An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 395, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_http.py", line 77, in send
    raise OfflineModeIsEnabled(
huggingface_hub.errors.OfflineModeIsEnabled: Cannot reach https://huggingface.co/QuanSun/EVA-CLIP/resolve/main/EVA02_CLIP_L_336_psz14_s6B.pt: offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.

**Comment by Lethita** [comment]
temporary solution
```
@@ -239,7 +239,7 @@ class PulidFluxEvaClipLoader:
     def load_eva_clip(self):
         from .eva_clip.factory import create_model_and_transforms
 
-        model, _, _ = create_model_and_transforms('EVA02-CLIP-L-14-336', 'eva_clip', force_custom_clip=True)
+        model, _, _ = create_model_and_transforms('EVA02-CLIP-L-14-336', '/ComfyUI/models/clip/EVA02_CLIP_L_336_psz14_s6B.pt', force_custom_clip=True)
```

**Comment by LiJT** [comment]
> temporary solution
> 
> ```
> @@ -239,7 +239,7 @@ class PulidFluxEvaClipLoader:
>      def load_eva_clip(self):
>          from .eva_clip.factory import create_model_and_transforms
>  
> -        model, _, _ = create_model_and_transforms('EVA02-CLIP-L-14-336', 'eva_clip', force_custom_clip=True)
> +        model, _, _ = create_model_and_transforms('EVA02-CLIP-L-14-336', '/ComfyUI/models/clip/EVA02_CLIP_L_336_psz14_s6B.pt', force_custom_clip=True)
> ```

hello! 
'/ComfyUI/models/clip/EVA02_CLIP_L_336_psz14_s6B.pt'
should be corrected as
'./ComfyUI/models/clip/EVA02_CLIP_L_336_psz14_s6B.pt'
